### ISSUE TITLE
InitializingBean instead of @Postconstruct

### ISSUE THREAD

**Issue by Deviad** [selimyanat/SpringBoot-Ethereum-Transaction-Tracker-Demo#1]
Hello,
I was looking at your repo since I could not subscribe to infura websocket with web3j.
Thank you for the valuable info in this repo.
You might consider using InitializingBean with Spring and afterPropertiesSet() since @PostConstruct is said to be deprecated.

You can have a look at my project Clarity if you wish.

https://github.com/selimyanat/web3j-api-demo/blob/67436615e494ef6de059ce0e432dd8b773350152/src/main/java/com/sy/web3j/api/demo/blockchain/BlockchainService.java#L78

**Comment by selimyanat** [comment]
Hello,
Sorry to catch up a year later .... thanks for the heads-up I have proceeded to the update in the repo.
